### ISSUE TITLE
click on the edit and resender button but it doesn't work 

### ISSUE THREAD

**Issue by zarek-zhao** [microsoft/edge-devtools-network-console#125]
hello, Dear developer, I click on the edit and resender button but it doesn't work 

this is my environmental information:

edge:
version124.0.2478.10 dev (64 位)

window11  23H2

**Comment by AkramiPro** [comment]
same here

`Version 123.0.2420.65 (Official build) (64-bit)`

**Comment by MansourJabin** [comment]
It happened to me too after the update
`Version 123.0.2420.65 (Official build) (64-bit)
`

**Comment by captainbrosset** [comment]
Thanks for reaching out. Unfortunately this trool has been very low on our priority list in the recent past, and has never made it out of experimental state. We have no current plan to fix this at the very moment. I've been using this issue to track Network Console problems: https://github.com/MicrosoftEdge/DevTools/issues/224 So let me close this one and ask you all to use that other issue instead.
Thank you for your understanding.
