### ISSUE TITLE
Edit and resend doesn't open the network console

### ISSUE THREAD

**Issue by Hundsmuhlen** [microsoft/edge-devtools-network-console#129]
I am trying to edit and resend a specifc request. On right click on edit and resend nothing happens. This is not just limited to one specific type of request or website. 

Similar problem on Stackoverflow: https://stackoverflow.com/questions/78273237/microsoft-edge-edit-and-resend-not-showing-up

I am on Microsoft Edge for Business
Version 124.0.2478.51 (Official build) (64-bit)

**Comment by captainbrosset** [comment]
Sorry about this. We're aware of this issue and are currently tracking it in https://github.com/MicrosoftEdge/DevTools/issues/224.
