### ISSUE TITLE
Network console fails to load with HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by tummalasujith** [microsoft/edge-devtools-network-console#130]
When trying to open network console either through Edit and Resend or directly by selecting network console, it doesn't load and shows a blank page with HTTP/1.1 404 Not Found.

![image](https://github.com/user-attachments/assets/709e6e4b-17ee-47f3-b7f2-a54ade17bb19)

I tried in different machines and profiles to make sure it is not my configurations.

**Comment by captainbrosset** [comment]
Thanks for filing. This issue is tracked on the main DevTools issues repo here: https://github.com/MicrosoftEdge/DevTools/issues/268
So, closing this one as duplicate.
