### ISSUE TITLE
Error message appears cut off in web application host

### ISSUE THREAD

**Issue by bgoddar** [microsoft/edge-devtools-network-console#48]
Send an invalid request in the webhost, such as to localhost:3000, and the resulting error message appears cut off when resizing the splitter:
![image](https://user-images.githubusercontent.com/42152559/105247201-3f606200-5b29-11eb-8294-c845da008978.png)

![image](https://user-images.githubusercontent.com/42152559/105247253-599a4000-5b29-11eb-8084-70134c265087.png)

**Comment by bgoddar** [comment]
First reproed when reviewing #43

**Comment by robpaveza** [comment]
Pretty sure this was introduced in #43
