### ISSUE TITLE
Can't get detail from request when click edit and resend

### ISSUE THREAD

**Issue by web4zn** [microsoft/edge-devtools-network-console#89]
when you click the edit and resend, can't get url and body from request.
The title of the resend section is POST *, missing the url. 
And the body content keep loading.......

**Comment by qzstudio** [comment]
Yes, I have too. Very distressed

**Comment by JoernBerkefeld** [comment]
+1
anyone reading this?

**Comment by captainbrosset** [comment]
This repository hasn't been super closely monitored. The Network Console tool is available within DevTools directly. So it would be great if you could post a new issue on this repo instead: https://github.com/MicrosoftEdge/DevTools.
Thanks a lot for your understanding.

**Comment by vexkox** [comment]
Hallo i hope identitet do somthing stupid. I am all New to this git hub?

Sendt fra Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by captainbrosset** [comment]
Closing since this is now tracked at https://github.com/MicrosoftEdge/DevTools/issues/224

**Comment by bstring23** [comment]
> +1 anyone reading this?

maybe  
**yes reading copy**
[Coverage-20231113T134551.json](https://github.com/microsoft/edge-devtools-network-console/files/15447010/Coverage-20231113T134551.json)
