### ISSUE TITLE
Delete icons are black on black in dark theme

### ISSUE THREAD

**Issue by bgoddar** [microsoft/edge-devtools-network-console#9]
![image](https://user-images.githubusercontent.com/42152559/84186001-afabee80-aa44-11ea-881a-7b2348dd235b.png)

The delete icons in the header table are black on black when using the dark theme version. makes it hard to see.

**Comment by robpaveza** [comment]
This has been fixed.

**Comment by robpaveza** [comment]
Was fixed in #11
